name: Python Solutions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Test
      run: |
        find . -name 'test.py' -print0 | xargs -0 -n1 python2.7
